### ISSUE TITLE
hoooly fuck

### ISSUE THREAD

**Issue by 9vj** [trapaholics/konas#1]
is this the cool k client ive been hearing about ???

**Comment by dopepushing** [comment]
Yeah

**Comment by GentlemanMC** [comment]
uncooled k logo client

**Comment by 6sn** [comment]
booger breatgh

**Comment by 6sn** [comment]
Look at this Retard sending Me roblox Shit Gooood Dayuuuuuum

**Comment by 6sn** [comment]
LOL

**Comment by 6sn** [comment]
Niggas B Talkin Shit On Discord Actin Like Dey Hard But In Reality Dey Making Shitty Videos About Swift Surround Buggin Forcin Dey Voice To Be Deep

**Comment by master7720** [comment]
ima sorry but WHO?
